version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_PASS=admin123
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_VHOST=Staging
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - minha-rede

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: cachemanager
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - minha-rede

  seq:
    image: "datalust/seq"
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 9000:80
    networks:
      - minha-rede
  
  cash-manager-daily-api:
    image: cash-manager-daily-api
    depends_on:
      - mongo
      - rabbitmq
      - seq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft__AspNetCore=Warning
      - ConnectionStrings__Mongo=mongodb://admin:admin123@mongo:27017/?retryWrites=true&w=majority
      - ConnectionStrings__RabbitMq=amqp://admin:admin123@rabbitmq:5672/Staging
      - MongoSettings__DatabaseName=cachemanager
      - RabbitMqSettings__QueueName=cache-manager-transactions
      - RabbitMqSettings__ExchangeName=cache-manager-exchange
      - RabbitMqSettings__ExchangeType=direct
      - RabbitMqSettings__RoutingKey=transactions.#
      - LogSeq__Host=http://seq:5341/
      - LogSeq__Env=Development
      - LogSeq__Project=CashManager.Daily.Api
    build:
      context: .
      dockerfile: src/CashManager.Daily.Api/Dockerfile
    ports:
      - "5079:80"
    networks:
      - minha-rede

  cash-manager-report-api:
    image: cash-manager-report-api
    depends_on:
      - mongo
      - rabbitmq
      - seq
      - cash-manager-daily-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft__AspNetCore=Warning
      - ConnectionStrings__Mongo=mongodb://admin:admin123@mongo:27017/?retryWrites=true&w=majority
      - ConnectionStrings__RabbitMq=amqp://admin:admin123@rabbitmq:5672/Staging
      - MongoSettings__DatabaseName=cachemanager
      - RabbitMqSettings__QueueName=cache-manager-transactions
      - RabbitMqSettings__ExchangeName=cache-manager-exchange
      - RabbitMqSettings__ExchangeType=direct
      - RabbitMqSettings__RoutingKey=transactions.#
      - LogSeq__Host=http://seq:5341/
      - LogSeq__Env=Development
      - LogSeq__Project=CashManager.Report.Api
    build:
      context: .
      dockerfile: src/CashManager.Report.Api/Dockerfile
    ports:
      - "5080:80"
    networks:
      - minha-rede

networks:
  minha-rede: